/** Read-only real browser verification of existing negotiation chats. */
import{chromium}from'playwright';import assert from'node:assert/strict';import{mkdir,writeFile}from'node:fs/promises';import{createHash}from'node:crypto';
const base=process.env.BASE_URL||'http://localhost:3001',out=process.env.SCREENSHOT_DIR||'/tmp/grove-chat-ui';await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const page=await browser.newPage({viewport:{width:1440,height:1060}}),errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!['GET','HEAD','OPTIONS'].includes(r.method()))writes.push(r.url());});const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
try{
 const boot=await(await page.request.get(`${base}/api/bootstrap`)).json(),run=boot.currentRun;assert.ok(run&&['reviewing','complete','flyer_ready'].includes(run.status));const before=await(await page.request.get(`${base}/api/runs/${run.id}`)).json(),transcript=await(await page.request.get(`${base}/api/runs/${run.id}/messages`)).json();
 await page.goto(base,{waitUntil:'domcontentloaded'});await page.waitForFunction(id=>document.querySelector('main')?.dataset.runId===id,run.id);await page.locator('.nav-item').filter({hasText:'Activity'}).click();await page.getByText('Actual Band records',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('Filter messages by product').inputValue(),'strawberries');await page.screenshot({path:`${out}/00-default-strawberry-chat.png`,fullPage:false});await page.getByLabel('Filter messages by product').selectOption('apples');const supplier=await page.getByLabel('Select supplier conversation').inputValue();const expected=transcript.messages.filter(m=>m.skuIds.includes('apples')&&((m.from==='fruit-buyer'&&m.to===supplier)||(m.from===supplier&&m.to==='fruit-buyer'))).sort((a,b)=>Date.parse(a.createdAt)-Date.parse(b.createdAt)||a.id.localeCompare(b.id));
 assert.deepEqual(expected.map(m=>m.type),['rfq','quote','counteroffer','quote','accept_quote','decision']);assert.deepEqual(await page.locator('.chat-message').evaluateAll(nodes=>nodes.map(node=>node.dataset.messageId)),expected.map(m=>m.id));assert.equal(await page.locator('.chat-outgoing').count(),3);assert.equal(await page.locator('.chat-incoming').count(),3);
 const counter=page.locator(`[data-message-id="${expected[2].id}"]`),reply=page.locator(`[data-message-id="${expected[3].id}"]`);assert.ok((await counter.locator('.chat-text').innerText()).includes('$30.17'));assert.ok((await reply.locator('.chat-text').innerText()).includes('$30.17'));await counter.scrollIntoViewIfNeeded();await reply.scrollIntoViewIfNeeded();await page.screenshot({path:`${out}/01-apples-chat.png`,fullPage:false});
 await page.getByLabel('Filter messages by product').selectOption('avocados');assert.equal(await page.getByLabel('Select supplier conversation').inputValue(),'supplier-import');assert.equal(await page.locator('.chat-message').count(),8);assert.equal(await page.locator('.chat-kind').filter({hasText:'Counteroffer'}).count(),3);const avocadoText=await page.locator('.chat-log').innerText();assert.ok(avocadoText.includes('$49.63')&&avocadoText.includes('$41.96')&&avocadoText.includes('$16.30'));await page.locator('.chat-log').evaluate(node=>node.scrollTop=0);await page.screenshot({path:`${out}/02-avocado-chat.png`,fullPage:false});
 const first=page.locator('.chat-message').first();await first.locator('.chat-details>summary').click();await first.locator('.message-json>summary').focus();await page.keyboard.press('Enter');const id=await first.getAttribute('data-message-id');assert.deepEqual(JSON.parse(await first.locator('pre').textContent()),transcript.messages.find(m=>m.id===id).payload);await first.locator('.chat-details>summary').click();
 await page.getByRole('button',{name:'Council',exact:true}).click();await page.getByText('Actual Band records',{exact:true}).waitFor();assert.equal(await page.locator('.chat-message').count(),2);assert.equal(await page.locator('.chat-outgoing').count(),1);assert.equal(await page.locator('.chat-incoming').count(),1);assert.ok((await page.locator('.chat-log').innerText()).includes('Approved'));await page.locator('.chat-log').scrollIntoViewIfNeeded();await page.screenshot({path:`${out}/03-council-chat.png`,fullPage:false});
 await page.getByRole('button',{name:'Messages',exact:true}).click();await page.getByText('Actual Band records',{exact:true}).waitFor();await page.setViewportSize({width:390,height:844});await page.locator('.chat-log').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`${out}/04-mobile-chat.png`,fullPage:false});
 await page.locator('.nav-item').filter({hasText:'Purchasing'}).click();await page.getByRole('button',{name:'Inspect Strawberries',exact:true}).click();await page.getByRole('button',{name:'View messages for Strawberries',exact:true}).click();await page.getByText('Actual Band records',{exact:true}).waitFor();assert.equal(await page.getByLabel('Filter messages by product').inputValue(),'strawberries');assert.ok(await page.locator('.chat-kind').filter({hasText:'Counteroffer'}).count()>0);
 await page.getByRole('button',{name:'All messages',exact:true}).click();await page.getByText('Actual Band records',{exact:true}).waitFor();assert.ok(await page.locator('.transcript-message').count()>0);
 const after=await(await page.request.get(`${base}/api/runs/${run.id}`)).json();assert.equal(hash(before),hash(after));assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);const report={passed:true,runId:run.id,status:run.status,defaultThread:{sku:'strawberries',supplier,messages:expected.length},checks:['Actual6-message alternating chain including counteroffer and supplier reply','Three avocado counteroffer rounds preserve actual nonmonotonic prices','Buyer/manager Council uses opposing request/reply bubbles','Original batched JSON unchanged under optional details','Mobile fits; product drawer opens correct chat; archive retained','Current reviewing run unchanged; no errors or mutating requests'],beforeHash:hash(before),afterHash:hash(after),errors,writes};await writeFile(`${out}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
