/** Explicit real-provider E2E. Starts ONE live run and incurs Glasser/ZooWork/Band calls.
 * Run manually: node tests/live.browser.mjs --live-providers
 * Optional BASE_URL, SCREENSHOT_DIR, CHROMIUM_PATH. Never invoked by default tests.
 * All workflow mutations use visible UI. API requests below are read-only assertions.
 */
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
if(!process.argv.includes('--live-providers'))throw new Error('Explicit --live-providers flag required: this E2E makes real provider calls and creates one live purchasing run.');
const base=process.env.BASE_URL||'http://localhost:3001',output=process.env.SCREENSHOT_DIR||'/tmp/grove-real-e2e';
await mkdir(output,{recursive:true});
const get=async(path)=>{const response=await fetch(`${base}${path}`);assert.equal(response.ok,true,`GET ${path}`);return response.json();};
const frozen=(run)=>Object.fromEntries(['id','mode','status','store','budget','items','quotes','decisions','events','evidence','promotions','promotionRevision','flyer','useTrends','trends'].map(key=>[key,run[key]]));
const digest=(value)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const before=await get('/api/bootstrap'),previous=before.currentRun,previousHash=previous?digest(frozen(previous)):null;
const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1060},deviceScaleFactor:1});
await context.tracing.start({screenshots:true,snapshots:true,sources:true});
const errors=[],consoleErrors=[],checks=[];const result={passed:false,startedAt:new Date().toISOString(),baseURL:base,previousRunId:previous?.id,checks,errors,consoleErrors};let runId;
try{
 const page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});
 await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('.hero').waitFor();
 await page.locator('.nav-item').filter({hasText:'Social trends'}).click();await page.getByLabel('Produce topic',{exact:true}).selectOption('cucumbers');
 const refreshed=page.waitForResponse(response=>response.url().endsWith('/api/trends/refresh')&&response.request().method()==='POST',{timeout:120000});
 await page.getByRole('button',{name:'Refresh social sources',exact:true}).click();assert.equal(await page.getByLabel('Produce topic',{exact:true}).isDisabled(),true);
 const refreshResponse=await refreshed;assert.equal(refreshResponse.ok(),true);const report=await refreshResponse.json();assert.equal(report.querySkuId,'cucumbers');assert.ok(report.providers.every(provider=>provider.status==='live'));assert.ok(report.signals.some(signal=>signal.platform==='tiktok'));assert.ok(report.signals.some(signal=>signal.platform==='x'));assert.ok(report.eligibleSkuIds.includes('cucumbers'));
 await page.getByRole('heading',{name:'TikTok',exact:true}).waitFor();await page.getByRole('heading',{name:'X',exact:true}).waitFor();await page.getByRole('button',{name:'Refresh social sources',exact:true}).waitFor();
 for(const href of await page.locator('.trend-signal a').evaluateAll(nodes=>nodes.map(node=>node.href)))assert.ok(/^https?:\/\//.test(href));
 const impact=report.impactPreview.find(item=>item.skuId==='cucumbers');assert.ok(impact);assert.ok((await page.locator('.trend-impact').innerText()).includes(`${impact.baselineOrderUnits} → ${impact.adjustedOrderUnits}`));
 await page.screenshot({path:`${output}/01-real-social-sources.png`,fullPage:true});checks.push('Actual visible cucumber refresh returns TikTok + X sources, dates, eligible product and exact whole-case preview');
 Object.assign(result,{trendObservedAt:report.observedAt,trendTopic:report.querySkuId,trendSignalIds:report.signals.map(signal=>signal.id),trendCounts:Object.fromEntries(report.providers.map(provider=>[provider.platform,provider.count])),trendImpactPreview:report.impactPreview});
 await page.getByRole('button',{name:/^(Start purchasing run|New purchasing run)$/}).click();await page.getByLabel('Agent execution').selectOption('live');const optin=page.getByRole('checkbox',{name:/Use fresh social-interest signals/});assert.equal(await optin.isChecked(),false);await optin.check();assert.ok((await page.getByRole('dialog').innerText()).includes(`${impact.baselineOrderUnits} → ${impact.adjustedOrderUnits}`));await page.screenshot({path:`${output}/02-live-optin.png`});
 const started=page.waitForResponse(response=>response.url().endsWith('/api/runs')&&response.request().method()==='POST');await page.getByRole('button',{name:'Start purchasing',exact:true}).click();const startResponse=await started;assert.equal(startResponse.ok(),true);const initial=await startResponse.json();runId=initial.id;Object.assign(result,{runId});console.log(JSON.stringify({event:'live_run_started',runId,trendObservedAt:report.observedAt}));assert.equal(initial.mode,'live');assert.equal(initial.useTrends,true);
 let run=initial,last=-1;const deadline=Date.now()+360000;
 while(Date.now()<deadline){run=await get(`/api/runs/${runId}`);if(run.eventSeq!==last){console.log(JSON.stringify({event:'progress',runId,status:run.status,resolved:run.progress.resolved,suppliers:run.progress.suppliersResponded}));last=run.eventSeq;}if(['reviewing','complete','flyer_ready','failed','cancelled','interrupted'].includes(run.status))break;await page.waitForTimeout(5000);}
 assert.ok(['reviewing','complete','flyer_ready'].includes(run.status),run.error||run.status);assert.equal(run.error,undefined);assert.equal(run.decisions.length,24);assert.equal(run.progress.suppliersResponded,8);assert.ok(run.decisions.every(decision=>['accepted','unavailable','skipped'].includes(decision.outcome)));const accepted=run.decisions.filter(decision=>decision.outcome==='accepted');assert.ok(accepted.length>0);assert.ok(accepted.every(decision=>decision.receiptStatus==='confirmed'));assert.equal(run.budget.committedCents+run.budget.reservedCents+run.budget.unallocatedCents,run.budget.totalCents);assert.equal(JSON.stringify(run).includes('floorCaseCents'),false);
 const cucumber=run.items.find(item=>item.skuId==='cucumbers');assert.equal(cucumber.quantity,impact.adjustedOrderUnits);assert.equal(cucumber.demand.trendAdjustmentUnits,2);assert.equal(run.trends.observedAt,report.observedAt);
 await page.waitForFunction(id=>document.querySelector('main')?.dataset.runId===id&&document.body.innerText.includes('24 / 24 decisions resolved'),runId);await page.screenshot({path:`${output}/03-live-completed-overview.png`,fullPage:true});checks.push('One actual live run resolves all24 products with8suppliers, confirmed receipts, exact budget balance and frozen social input');
 await page.locator('.nav-item').filter({hasText:'Purchasing'}).click();await page.getByRole('button',{name:'Inspect Cucumbers',exact:true}).click();await page.getByRole('heading',{name:'Opted-in social-interest assumption',exact:true}).waitFor();if(run.decisions.find(decision=>decision.skuId==='cucumbers')?.outcome==='accepted')await page.getByText('Supplier receipt confirmed through Band.',{exact:false}).waitFor();await page.screenshot({path:`${output}/04-cucumber-proof.png`,fullPage:true});await page.getByRole('button',{name:'Close product details'}).click();
 assert.equal((await page.request.get(`${base}/api/runs/${runId}/god`)).status(),403);await page.getByRole('button',{name:'God mode',exact:true}).click();await page.getByRole('button',{name:'Open god view',exact:true}).click();await page.getByRole('button',{name:'Inspect private state'}).first().waitFor();assert.equal(await page.locator('.supplier-card').count(),8);await page.getByRole('button',{name:'Inspect private state'}).first().click();await page.getByRole('dialog').getByText('Minimum / case',{exact:true}).first().waitFor();await page.screenshot({path:`${output}/05-god-private-state.png`,fullPage:true});await page.getByRole('button',{name:'Close private details'}).click();await page.getByRole('button',{name:'Operator',exact:true}).click();assert.equal((await page.request.get(`${base}/api/runs/${runId}/god`)).status(),403);checks.push('Actual product detail shows frozen social assumption and confirmed receipt; God state authorized separately and revoked');
 await page.locator('.nav-item').filter({hasText:'Promotions'}).click();await page.getByRole('button',{name:'Approve promotion plan',exact:true}).click();await page.getByRole('button',{name:'Create approved flyer',exact:true}).click();await page.getByRole('button',{name:'Print flyer',exact:true}).waitFor();const final=await get(`/api/runs/${runId}`);assert.equal(final.flyer.status,'ready');assert.equal(final.promotions.length,3);for(const promotion of final.promotions){assert.ok(promotion.approved);const text=await page.locator('.flyer-offer').filter({has:page.getByRole('heading',{name:promotion.name,exact:true})}).innerText();assert.ok(text.includes((promotion.retailPriceCents/100).toFixed(2)));assert.ok(text.includes(`Available quantity: ${promotion.quantityCap} (${promotion.unit})`));}assert.ok(await page.locator('.flyer img').evaluate(img=>img.complete&&img.naturalWidth>0));await page.screenshot({path:`${output}/06-approved-flyer.png`,fullPage:true});await page.locator('.flyer').screenshot({path:`${output}/flyer.png`});checks.push('Approved flyer uses real-run frozen prices and quantity caps with generated artwork');
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(id=>document.querySelector('main')?.dataset.runId===id,runId);await page.locator('.hero').waitFor();await page.screenshot({path:`${output}/07-reload.png`});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('.nav-item').filter({hasText:'Social trends'}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`${output}/08-mobile.png`,fullPage:true});checks.push('Reload retains same actual run; overview and social research fit390px mobile');
 if(previous){const old=await get(`/api/runs/${previous.id}`);assert.equal(digest(frozen(old)),previousHash);checks.push('Earlier completed live run remains immutable');}
 assert.deepEqual(errors,[]);Object.assign(result,{passed:true,completedAt:new Date().toISOString(),runStatus:final.status,mode:final.mode,accepted:accepted.length,confirmedReceipts:accepted.length,suppliers:final.progress.suppliersResponded,resolved:final.progress.resolved,committedCents:final.budget.committedCents,unallocatedCents:final.budget.unallocatedCents,flyerUrl:final.flyer.url,promotions:final.promotions.map(({name,retailPriceCents,quantityCap,unit,startsAt,endsAt})=>({name,retailPriceCents,quantityCap,unit,startsAt,endsAt}))});
}catch(error){Object.assign(result,{error:error.message,failedAt:new Date().toISOString(),runId});console.error(error);process.exitCode=1;}
finally{await context.tracing.stop({path:`${output}/trace.zip`});await writeFile(`${output}/report.json`,JSON.stringify(result,null,2));await browser.close();console.log(JSON.stringify(result,null,2));}
