/** Read-only verification of human-readable existing live messages. No provider or purchasing actions. */
import {chromium} from 'playwright';import assert from 'node:assert/strict';import{mkdir,writeFile}from'node:fs/promises';import{createHash}from'node:crypto';
const base=process.env.BASE_URL||'http://localhost:3001',out=process.env.SCREENSHOT_DIR||'/tmp/grove-readable-ui';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1060}}),errors=[],writes=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!['GET','HEAD','OPTIONS'].includes(r.method()))writes.push(r.url());});
const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex'),money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v/100);
try{
 const boot=await(await page.request.get(`${base}/api/bootstrap`)).json(),run=boot.currentRun;assert.ok(run&&['reviewing','complete','flyer_ready'].includes(run.status));
 const before=await(await page.request.get(`${base}/api/runs/${run.id}`)).json(),transcript=await(await page.request.get(`${base}/api/runs/${run.id}/messages`)).json();
 await page.goto(base,{waitUntil:'domcontentloaded'});await page.waitForFunction(id=>document.querySelector('main')?.dataset.runId===id,run.id);await page.locator('.nav-item').filter({hasText:'Activity'}).click();await page.getByRole('button',{name:'All messages',exact:true}).click();await page.getByText('Actual Band records',{exact:true}).waitFor();
 assert.equal(await page.locator('.message-json[open]').count(),0);
 while(await page.getByRole('button',{name:/Show next \d+ messages/}).count())await page.getByRole('button',{name:/Show next \d+ messages/}).click();
 const cardFor=m=>page.locator(`[data-message-id="${m.id}"]`);
 const rfq=transcript.messages.find(m=>m.type==='rfq'&&m.payload.lines.length>3),rfqCard=cardFor(rfq);await rfqCard.getByRole('button',{name:`Show all ${rfq.payload.lines.length} products`,exact:true}).click();assert.equal(await rfqCard.locator('.readable-line').count(),rfq.payload.lines.length);for(const line of rfq.payload.lines)assert.ok((await rfqCard.locator(`[data-sku-id="${line.skuId}"]`).innerText()).includes(`${line.cases} case`));assert.equal(await rfqCard.locator('.message-json[open]').count(),0);
 checks.push('All RFQ product quantities readable without opening JSON');
 const quote=transcript.messages.find(m=>m.type==='quote'),quoteCard=cardFor(quote);if(quote.payload.quotes.length>3)await quoteCard.getByRole('button',{name:`Show all ${quote.payload.quotes.length} offers`}).click();for(const line of quote.payload.quotes){const text=await quoteCard.locator(`[data-sku-id="${line.skuId}"]`).innerText();assert.ok(text.includes(money(line.casePriceCents)));assert.ok(text.includes(`${money(line.landedCostCents)} total`));assert.ok(text.includes(`${money(line.freightCents)} freight`));}
 checks.push('Offers distinguish per-case price, whole-quote total and freight');
 for(const type of ['counteroffer','budget_request','budget_decision','accept_quote','decision']){const m=transcript.messages.find(m=>m.type===type);assert.ok(m);const text=await cardFor(m).locator('.readable-message').innerText();assert.ok(text.length>25);if(type==='counteroffer')assert.ok(text.includes(money(m.payload.lines[0].casePriceCents)));if(type==='budget_request')assert.ok(text.includes(money(m.payload.incrementCents)));if(type==='budget_decision')assert.ok(text.includes(m.payload.approve?'Approved':'Declined'));if(type==='accept_quote'){assert.ok(text.includes(money(m.payload.committedCostCents)));assert.ok(text.includes('supplier acknowledgment is recorded separately'));}if(type==='decision')assert.ok(text.includes('does not confirm delivery'));}
 checks.push('Counteroffers, requests, decisions, commitments and receipts use faithful readable sentences');
 await rfqCard.getByRole('button',{name:'Show fewer products'}).click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`${out}/01-readable-overview.png`,fullPage:false});
 await page.getByLabel('Filter messages by product').selectOption('apples');const firstQuote=page.locator('.transcript-message').filter({has:page.locator('.message-meta .pill').filter({hasText:'Supplier quote'})}).first();await firstQuote.scrollIntoViewIfNeeded();await page.screenshot({path:`${out}/02-readable-offer.png`,fullPage:false});
 const filteredRfq=cardFor(rfq);await filteredRfq.getByRole('button',{name:`Show all ${rfq.payload.lines.length} products`}).click();assert.equal(await filteredRfq.locator('.readable-line').count(),rfq.payload.lines.length);await filteredRfq.getByRole('button',{name:'Show fewer products'}).click();
 await page.setViewportSize({width:390,height:844});await firstQuote.scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`${out}/03-readable-mobile.png`,fullPage:false});
 const first=page.locator('.transcript-message').first();await first.locator('summary').focus();await page.keyboard.press('Enter');const firstId=await first.getAttribute('data-message-id');assert.deepEqual(JSON.parse(await first.locator('pre').textContent()),transcript.messages.find(m=>m.id===firstId).payload);
 await page.getByRole('button',{name:'Council',exact:true}).click();await page.getByText('Actual Band records',{exact:true}).waitFor();assert.ok((await page.locator('.chat-text').first().innerText()).includes('Requesting'));
 checks.push('Filtered batches still expand fully; mobile fits; keyboard JSON exact; Council shares readable format');
 const after=await(await page.request.get(`${base}/api/runs/${run.id}`)).json();assert.equal(hash(before),hash(after));assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);const report={passed:true,runId:run.id,status:run.status,messageCount:transcript.messages.length,beforeHash:hash(before),afterHash:hash(after),checks,errors,writes};await writeFile(`${out}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
