/** Destructive reset E2E only against tests/demo-server.ts (in-memory, no providers).
 * Start isolated server, build UI, then: node tests/reset.browser.mjs --isolated-demo
 * No interception. Every reset/start/approval goes through the visible UI.
 */
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
if(!process.argv.includes('--isolated-demo'))throw new Error('Require --isolated-demo and the in-memory tests/demo-server.ts; never reset production for this test.');
const base=process.env.BASE_URL||'http://127.0.0.1:3002';
const address=new URL(base);assert.ok(['127.0.0.1','localhost'].includes(address.hostname)&&address.port==='3002','Reset E2E is restricted to the isolated3002 server.');
const output=process.env.SCREENSHOT_DIR||'/tmp/grove-reset-ui';await mkdir(output,{recursive:true});
const read=async(path)=>{const response=await fetch(`${base}${path}`);assert.ok(response.ok);return response.json();};
const production=await(await fetch('http://127.0.0.1:3001/api/bootstrap')).json();const productionBefore=JSON.stringify(production.currentRun);
const browser=await chromium.launch({args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const context=await browser.newContext({viewport:{width:1440,height:1060}});await context.tracing.start({screenshots:true,snapshots:true});
const errors=[],checks=[];const result={passed:false,checks,errors,productionRunId:production.currentRun?.id};
try{
 const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));await page.goto(base,{waitUntil:'domcontentloaded'});
 const initial=await read('/api/bootstrap');assert.equal(initial.capabilities.live,false);const savedResearch=JSON.stringify(initial.trends);
 if(!initial.currentRun)await page.locator('.fresh-hero').waitFor();
 async function startSimulation(){await page.getByRole('button',{name:/^(Start purchasing run|New purchasing run)$/}).first().click();assert.equal(await page.getByLabel('Agent execution').inputValue(),'simulation');const started=page.waitForResponse(response=>response.url().endsWith('/api/runs')&&response.request().method()==='POST');await page.getByRole('button',{name:'Start purchasing',exact:true}).click();const response=await started;assert.ok(response.ok());const run=await response.json();assert.equal(run.mode,'simulation');await page.waitForFunction(id=>document.querySelector('main')?.dataset.runId===id&&document.body.innerText.includes('24 / 24 decisions resolved'),run.id);return run.id;}
 const firstId=await startSimulation();await page.locator('.nav-item').filter({hasText:'Promotions'}).click();await page.getByRole('button',{name:'Approve promotion plan',exact:true}).click();await page.getByRole('button',{name:'Create approved flyer',exact:true}).click();await page.getByRole('button',{name:'Print flyer',exact:true}).waitFor();
 const second=await context.newPage();second.on('pageerror',error=>errors.push(error.message));await second.goto(base,{waitUntil:'domcontentloaded'});await second.locator('.hero').waitFor();await second.locator('.nav-item').filter({hasText:'Purchasing'}).click();await second.getByRole('button',{name:'Inspect Apples',exact:true}).click();await second.getByRole('dialog').waitFor();
 await page.getByRole('button',{name:'God mode',exact:true}).click();await page.getByRole('button',{name:'Open god view',exact:true}).click();await page.getByRole('button',{name:'Inspect private state'}).first().waitFor();
 await page.getByRole('button',{name:'Reset demo',exact:true}).click();const resetDialog=page.getByRole('dialog',{name:'Reset this demo?'});await resetDialog.waitFor();assert.ok((await resetDialog.innerText()).includes('integration credentials'));await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);assert.equal((await read('/api/bootstrap')).currentRun.id,firstId);await page.getByRole('button',{name:'Reset demo',exact:true}).click();await resetDialog.getByRole('button',{name:'Keep demo',exact:true}).click();assert.equal((await read('/api/bootstrap')).currentRun.id,firstId);checks.push('Escape and Keep demo both dismiss confirmation without changing the saved run');
 await page.getByRole('button',{name:'Reset demo',exact:true}).click();await page.screenshot({path:`${output}/01-reset-confirmation.png`});await resetDialog.getByRole('button',{name:'Reset demo',exact:true}).focus();await page.keyboard.press('Tab');assert.equal(await resetDialog.getByRole('button',{name:'Keep demo',exact:true}).evaluate(element=>document.activeElement===element),true);
 const resetResponse=page.waitForResponse(response=>response.url().endsWith('/api/demo/reset')&&response.request().method()==='POST');await resetDialog.getByRole('button',{name:'Reset demo',exact:true}).click();const reset=await(await resetResponse).json();assert.equal(reset.reset,true);assert.ok(reset.clearedRuns>=1);assert.equal(reset.bootstrap.currentRun,null);await page.locator('.fresh-hero').waitFor();await second.locator('.fresh-hero').waitFor();assert.equal(await second.getByRole('dialog').count(),0);assert.equal(await page.getByRole('button',{name:'God mode',exact:true}).isDisabled(),true);assert.equal(await page.locator('main').getAttribute('data-run-id'),null);assert.equal((await page.request.get(`${base}/api/runs/${firstId}/god`)).status(),403);checks.push('Actual reset clears both open tabs, closes stale product details and revokes God access');
 await page.screenshot({path:`${output}/02-empty-overview.png`,fullPage:true});await page.screenshot({path:`${output}/02-empty-overview-viewport.png`});assert.equal(await page.locator('.stat').count(),0);assert.equal(await page.getByRole('button',{name:'Start purchasing run',exact:true}).count(),1);assert.ok((await page.locator('.fresh-readiness').innerText()).includes('Setup needed'));
 await page.locator('.nav-item').filter({hasText:'Purchasing'}).click();assert.equal(await page.locator('.product-table tbody tr').count(),24);assert.equal(await page.getByText('Not started',{exact:true}).count(),24);await page.getByRole('button',{name:'Inspect Apples',exact:true}).click();await page.getByRole('dialog').getByText('Not allocated',{exact:true}).waitFor();await page.keyboard.press('Escape');
 await page.locator('.nav-item').filter({hasText:'Agent network'}).click();assert.equal(await page.locator('.supplier-card').count(),8);assert.equal(await page.getByText('Ready for a run',{exact:true}).count(),8);assert.equal(await page.getByRole('button',{name:'Inspect private state'}).count(),0);
 await page.locator('.nav-item').filter({hasText:'Activity'}).click();await page.getByText('No conversations yet',{exact:true}).waitFor();assert.equal(await page.getByText('Committed purchases',{exact:true}).count(),0);
 await page.locator('.nav-item').filter({hasText:'Promotions'}).click();await page.getByText('Your first flyer starts with a purchase',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Print flyer',exact:true}).count(),0);
 await page.locator('.nav-item').filter({hasText:'Social trends'}).click();await page.getByRole('heading',{name:'TikTok',exact:true}).waitFor();assert.equal(JSON.stringify((await read('/api/bootstrap')).trends),savedResearch);checks.push('Every no-run tab is coherent; catalog/network stay useful, prior metrics/messages/flyer disappear, cached research survives');
 await page.waitForTimeout(5500);await page.reload({waitUntil:'domcontentloaded'});await page.locator('.fresh-hero').waitFor();assert.equal((await read('/api/bootstrap')).currentRun,null);await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`${output}/03-empty-mobile.png`,fullPage:true});await page.setViewportSize({width:1440,height:1060});checks.push('Empty state survives stale-poll interval and reload;390px mobile has no overflow');
 const secondId=await startSimulation();assert.notEqual(secondId,firstId);const newRun=await read(`/api/runs/${secondId}`);assert.equal(newRun.decisions.length,24);assert.equal(newRun.progress.suppliersResponded,8);assert.equal(newRun.mode,'simulation');await page.screenshot({path:`${output}/04-new-simulation.png`,fullPage:true});checks.push('Fresh simulation starts from empty state and resolves24 products with8suppliers without provider calls');
 const productionAfter=await(await fetch('http://127.0.0.1:3001/api/bootstrap')).json();assert.equal(JSON.stringify(productionAfter.currentRun),productionBefore);assert.deepEqual(errors,[]);Object.assign(result,{passed:true,clearedRunId:firstId,newSimulationRunId:secondId,productionUnchanged:true});
}catch(error){result.error=error.message;process.exitCode=1;console.error(error);}finally{await context.tracing.stop({path:`${output}/trace.zip`});await writeFile(`${output}/report.json`,JSON.stringify(result,null,2));await browser.close();console.log(JSON.stringify(result,null,2));}
