/** Read-only browser verification against an existing live run.
 * BASE_URL=http://localhost:3001 node tests/transcript.browser.mjs
 * No run creation, provider calls, reset, approval, or network interception.
 */
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const baseURL=process.env.BASE_URL||'http://localhost:3001';
const output=process.env.SCREENSHOT_DIR||'/tmp/grove-transcript-ui';
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1060}});
await context.tracing.start({screenshots:true,snapshots:true,sources:true});
const errors=[],checks=[],writes=[];
const page=await context.newPage();
page.on('pageerror',error=>errors.push(error.message));
page.on('request',request=>{if(!['GET','HEAD','OPTIONS'].includes(request.method()))writes.push({method:request.method(),url:request.url()});});
const hash=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
let runId,beforeHash;
try{
 const bootstrap=await(await page.request.get(`${baseURL}/api/bootstrap`)).json();
 assert.ok(bootstrap.currentRun,'Requires an existing run; this test never creates one');
 runId=typeof bootstrap.currentRun==='string'?bootstrap.currentRun:bootstrap.currentRun.id;
 const before=await(await page.request.get(`${baseURL}/api/runs/${runId}`)).json();
 assert.equal(before.mode,'live');
 assert.ok(['reviewing','complete','flyer_ready'].includes(before.status),'Run must be stable before a read-only preservation check');
 beforeHash=hash(before);
 const transcriptResponse=await page.request.get(`${baseURL}/api/runs/${runId}/messages`);
 assert.equal(transcriptResponse.status(),200);
 const transcript=await transcriptResponse.json();
 assert.equal(transcript.source,'band');
 assert.ok(transcript.messages.length>0);
 assert.equal(new Set(transcript.messages.map(message=>message.id)).size,transcript.messages.length);
 assert.equal(JSON.stringify(transcript).includes('floorCaseCents'),false);
 const chronological=[...transcript.messages].sort((a,b)=>Date.parse(a.createdAt)-Date.parse(b.createdAt)||a.id.localeCompare(b.id));
 await page.goto(baseURL,{waitUntil:'domcontentloaded'});
 await page.waitForFunction(id=>document.querySelector('main')?.dataset.runId===id,runId);
 await page.locator('.nav-item').filter({hasText:'Activity'}).click();
 await page.getByText('Actual Band records',{exact:true}).waitFor();
 assert.equal(await page.locator('.transcript-message').count(),Math.min(20,transcript.messages.length));
 assert.deepEqual(await page.locator('.transcript-message').evaluateAll(nodes=>nodes.map(node=>node.dataset.messageId)),chronological.slice(0,20).map(message=>message.id));
 checks.push('Actual stored Band records are deduplicated and displayed oldest first');
 const first=page.locator('.transcript-message').first();
 const summary=first.locator('summary');
 await summary.focus();await page.keyboard.press('Enter');
 assert.deepEqual(JSON.parse(await first.locator('pre').textContent()),chronological[0].payload);
 assert.equal(await first.locator('time').getAttribute('datetime'),chronological[0].createdAt);
 assert.equal(await first.locator('.message-delivery .done').count(),['sent','received','processed'].filter(stage=>chronological[0].transport[stage]).length);
 await page.screenshot({path:`${output}/01-messages-desktop.png`,fullPage:false});
 await summary.click();
 checks.push('Keyboard-expandable JSON exactly matches the saved payload, timestamp and transport confirmations');
 if(transcript.messages.length>20){await page.getByRole('button',{name:/Show next/}).click();assert.equal(await page.locator('.transcript-message').count(),Math.min(40,transcript.messages.length));}
 await page.getByLabel('Filter messages by product').selectOption('strawberries');
 const filtered=chronological.filter(message=>message.skuIds.includes('strawberries'));
 assert.ok(filtered.length>0);
 assert.deepEqual(await page.locator('.transcript-message').evaluateAll(nodes=>nodes.map(node=>node.dataset.messageId)),filtered.slice(0,20).map(message=>message.id));
 assert.ok(filtered.some(message=>message.type==='budget_request'));
 assert.ok(filtered.some(message=>message.type==='budget_decision'));
 assert.ok(filtered.some(message=>message.payload?.kind==='purchase_receipt'));
 await page.screenshot({path:`${output}/02-product-filter.png`,fullPage:false});
 checks.push('Product filtering retains buyer/supplier exchanges, manager budget decisions and explicit purchase receipts');
 await page.getByRole('button',{name:'Decision summaries',exact:true}).click();
 await page.getByText('Application summaries of recorded outcomes; these are not verbatim agent messages.').waitFor();
 await page.locator('.nav-item').filter({hasText:'Purchasing'}).click();
 await page.getByRole('button',{name:'Inspect Apples',exact:true}).click();
 await page.getByRole('button',{name:'View messages for Apples',exact:true}).click();
 await page.getByText('Actual Band records',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('Filter messages by product').inputValue(),'apples');
 checks.push('Product detail opens its actual transcript; derived decision summaries remain clearly separate');
 await page.getByRole('button',{name:'Refresh messages',exact:true}).click();
 await page.getByText('Actual Band records',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.locator('.transcript-message').first().locator('summary').click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 const pre=page.locator('.transcript-message').first().locator('pre');
 assert.equal(await pre.evaluate(element=>element.getBoundingClientRect().right<=innerWidth),true);
 await page.locator('.transcript-message').first().scrollIntoViewIfNeeded();
 await page.screenshot({path:`${output}/03-messages-mobile.png`,fullPage:false});
 checks.push('Mobile transcript and expanded JSON remain inside the viewport');
 await page.reload({waitUntil:'domcontentloaded'});
 await page.waitForFunction(id=>document.querySelector('main')?.dataset.runId===id,runId);
 await page.locator('.nav-item').filter({hasText:'Activity'}).click();
 await page.getByText('Actual Band records',{exact:true}).waitFor();
 const after=await(await page.request.get(`${baseURL}/api/runs/${runId}`)).json();
 assert.equal(hash(after),beforeHash,'Read-only review preserves the complete current run snapshot');
 assert.deepEqual(writes,[],'Browser made no mutating requests');
 assert.deepEqual(errors,[]);
 checks.push('Reload restores the same run; full run snapshot unchanged; no mutating requests or browser errors');
 const report={passed:true,runId,status:before.status,beforeHash,afterHash:hash(after),messageCount:transcript.messages.length,types:[...new Set(transcript.messages.map(message=>message.type))],omittedMessages:transcript.omittedMessages,truncated:transcript.truncated,checks,errors,writes};
 await writeFile(`${output}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await context.tracing.stop({path:`${output}/trace.zip`});await browser.close();}
