/** UI contracts only: intercepts mutations and never starts a production run or queries Glasser. */
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const base=process.env.BASE_URL||'http://localhost:5173';
const original=await(await fetch(`${base}/api/bootstrap`)).json();
const before=JSON.stringify(original.currentRun);
const now=new Date().toISOString();
let report={observedAt:now,status:'live',querySkuId:'cucumbers',eligibleSkuIds:['cucumbers'],totalChargedUsd:'0',providers:[{platform:'tiktok',status:'live',count:2},{platform:'x',status:'live',count:1}],signals:[{id:'test-tiktok',platform:'tiktok',skuIds:['cucumbers'],query:'cucumber salad',title:'Cucumber recipe interest — browser fixture',url:'https://www.tiktok.com/@example/video/123',postedAt:now,observedAt:now,engagement:{views:2400},source:'Glasser',signalType:'social_interest',provenGrowth:false},{id:'test-unsafe',platform:'tiktok',skuIds:['cucumbers'],query:'cucumber salad',title:'Unsafe link fixture',url:'javascript:alert(1)',postedAt:now,observedAt:now,source:'Glasser',signalType:'social_interest',provenGrowth:false},{id:'test-x',platform:'x',skuIds:['cucumbers'],query:'cucumber salad',title:'Cucumber conversation with unknown post date',url:'https://x.com/example/status/123',observedAt:now,source:'Glasser',signalType:'social_interest',provenGrowth:false}]};
const browser=await chromium.launch({args:['--no-sandbox'],...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
const errors=[],checks=[];checks.push=(...items)=>{console.log(items.join('; '));return Array.prototype.push.apply(checks,items);};let failBootstrap=true,postBody,refreshCount=0;
try{const page=await browser.newPage({viewport:{width:1440,height:1060}});page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/bootstrap',route=>{if(failBootstrap){return route.fulfill({status:503,json:{error:'Temporary bootstrap failure'}});}return route.fulfill({json:{...original,trends:report}});});
await page.route('**/api/runs/**',route=>route.request().url().endsWith('/events')?route.fulfill({contentType:'text/event-stream',body:': browser fixture\n\n'}):route.fulfill({json:original.currentRun}));
await page.route('**/api/runs',route=>{postBody=route.request().postDataJSON();return route.fulfill({status:400,json:{error:'Browser fixture: no production run created.'}});});
await page.route('**/api/trends/refresh',async route=>{refreshCount++;await new Promise(resolve=>setTimeout(resolve,500));assert.equal(route.request().postDataJSON().skuId,'apples');report={...report,status:'partial',querySkuId:'apples',eligibleSkuIds:[],providers:[{platform:'tiktok',status:'live',count:1},{platform:'x',status:'unavailable',count:0,error:'Browser fixture: X temporarily unavailable'}],signals:[{...report.signals[0],id:'old-fixture',skuIds:['apples'],postedAt:'2000-01-01T12:00:00Z',title:'Old post — no fresh demand signal'}]};return route.fulfill({json:report});});
await page.goto(base,{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Try again',exact:true}).waitFor();failBootstrap=false;await page.getByRole('button',{name:'Try again',exact:true}).click();await page.locator('.hero').waitFor();checks.push('Bootstrap failure has a working retry');
await page.locator('.nav-item').filter({hasText:'Purchasing'}).click();await page.getByRole('button',{name:'Supplier comparison',exact:true}).click();const row=page.getByRole('button',{name:'Inspect Apples supplier comparison',exact:true});await row.focus();await page.keyboard.press('Enter');await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');assert.equal(await row.evaluate(element=>document.activeElement===element),true);checks.push('Supplier comparison is keyboard accessible and restores focus');
await page.locator('.nav-item').filter({hasText:'Social trends'}).click();await page.getByRole('heading',{name:'TikTok',exact:true}).waitFor();await page.getByRole('heading',{name:'X',exact:true}).waitFor();assert.equal(await page.locator('.trend-signal a').count(),2);assert.equal(await page.locator('a[href^="javascript:"],a[href^="data:"]').count(),0);assert.ok((await page.locator('body').innerText()).includes('Posted Unknown'));assert.ok((await page.locator('body').innerText()).includes('not verified trends in 94110'));checks.push('Both platforms, unknown dates, geographic caveat, and safe source links');
await page.getByRole('button',{name:'New purchasing run',exact:true}).click();const checkbox=page.getByRole('checkbox',{name:/Use fresh social-interest signals/});assert.equal(await checkbox.isChecked(),false);assert.ok((await page.getByRole('dialog').innerText()).includes('Eligible products: Cucumbers'));await checkbox.check();const dialog=page.getByRole('dialog');const first=dialog.locator('button').first();await dialog.getByRole('button',{name:'Start purchasing',exact:true}).focus();await page.keyboard.press('Tab');assert.equal(await first.evaluate(element=>document.activeElement===element),true);await dialog.getByRole('button',{name:'Start purchasing',exact:true}).click();await dialog.getByRole('alert').filter({hasText:'no production run created'}).waitFor();assert.equal(postBody.useTrends,true);assert.equal(postBody.mode,'simulation');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'New purchasing run',exact:true}).click();assert.equal(await checkbox.isChecked(),false);await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();checks.push('Modal focus remains contained; opt-in is explicit, submitted, and reset for each new run');
await page.getByLabel('Produce topic',{exact:true}).selectOption('apples');await page.getByRole('button',{name:'Refresh social sources',exact:true}).click();assert.equal(await page.getByLabel('Produce topic',{exact:true}).isDisabled(),true);assert.ok((await page.locator('.trend-report-date').innerText()).includes('Topic: Cucumbers'));await page.getByText('Browser fixture: X temporarily unavailable',{exact:true}).waitFor();assert.equal(refreshCount,1);assert.ok((await page.locator('.trend-time').innerText()).includes('2000'));await page.getByRole('button',{name:'New purchasing run',exact:true}).click();assert.equal(await checkbox.isDisabled(),true);await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();checks.push('One curated refresh request and honest partial/empty state; ineligible opt-in disabled');
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks.push('Six-tab mobile layout and trend panels do not overflow');assert.deepEqual(errors,[]);
const after=await(await fetch(`${base}/api/bootstrap`)).json();assert.equal(JSON.stringify(after.currentRun),before,'Completed production run remains unchanged');console.log(JSON.stringify({passed:true,fixtureOnly:true,checks,errors,productionRunUnchanged:original.currentRun.id},null,2));
}finally{await browser.close();}
