import type {AgentTranscriptMessage,CatalogItem} from '../shared/types';
import {Check} from 'lucide-react';
import ReadableMessage from './ReadableMessage';
import {money,roleName} from './api';
const object=(value:unknown):Record<string,unknown>=>value!==null&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
const numeric=(value:unknown):value is number=>typeof value==='number'&&Number.isFinite(value);
const cases=(value:number)=>`${value} ${value===1?'case':'cases'}`;
export default function ChatMessage({message,messages,catalog,skuId,actor}:{message:AgentTranscriptMessage;messages:AgentTranscriptMessage[];catalog:CatalogItem[];skuId:string;actor:(id:string)=>string}){
 const data=object(message.payload),raw=(Array.isArray(data.lines)?data.lines:Array.isArray(data.quotes)?data.quotes:[]).map(object),line=raw.find(item=>item.skuId===skuId)||{},item=catalog.find(product=>product.id===skuId),name=item?.name||skuId;
 const quantity=(value:number)=>`${value} ${item?.unit==='each'?name.toLowerCase():`${item?.unit||'unit'}${value===1?'':item?.unit==='bunch'?'es':'s'}`}`;
 const request=messages.find(other=>other.type==='budget_request'&&other.correlationId===message.correlationId&&other.from===message.to&&other.to===message.from),requested=object(request?.payload),increment=numeric(data.incrementCents)?data.incrementCents:requested.incrementCents;
 let summary='',detail='',label='Message';
 if(message.type==='rfq'){label='Quote request';summary=`Requesting a quote for ${numeric(line.cases)?`${cases(line.cases)} of `:''}${name}${numeric(line.quantity)?` (${quantity(line.quantity)})`:''}.`;}
 if(message.type==='quote'){label=numeric(line.round)&&line.round>0?`Quote reply · round ${line.round}`:'Initial offer';summary=`Offering ${name}${numeric(line.cases)?` · ${cases(line.cases)}`:''}${numeric(line.casePriceCents)?` at ${money(line.casePriceCents)} per case`:''}.`;detail=numeric(line.landedCostCents)?`${money(line.landedCostCents)} total${numeric(line.freightCents)?`, including ${money(line.freightCents)} freight`:''}.`:'';}
 if(message.type==='counteroffer'){label=`Counteroffer${numeric(data.round)?` · round ${data.round}`:''}`;summary=`Proposing ${numeric(line.casePriceCents)?`${money(line.casePriceCents)} per case`:'a new price'}${numeric(line.cases)?` for ${cases(line.cases)} of ${name}`:` for ${name}`}.`;}
 if(message.type==='budget_request'){label='Budget request';summary=`Requesting ${numeric(increment)?`${money(increment)} in additional budget`:'additional budget'} for ${name}.`;}
 if(message.type==='budget_decision'){label='Manager reply';summary=`${data.approve===true?'Approved':data.approve===false?'Declined':'Responded to'} ${numeric(increment)?`an additional ${money(increment)} for ${name}`:'the additional budget request'}.`;}
 if(message.type==='accept_quote'){label='Purchase commitment';summary=`Committing to ${numeric(data.quantity)?quantity(data.quantity):name}${numeric(data.committedCostCents)?` for ${money(data.committedCostCents)} total`:''}.`;detail='Supplier acknowledgment follows separately.';}
 if(data.kind==='purchase_receipt'){label='Supplier acknowledgment';summary=data.accepted===true?`Acknowledged the purchase commitment for ${name}.`:data.accepted===false?'Purchase commitment was not acknowledged.':'A purchase receipt was returned.';detail=data.accepted===true?'Receipt confirms the commitment, not delivery.':'This receipt does not confirm the commitment or delivery.';}
 const recordedReason=[data.reason,data.rationale,line.reason,line.rejectionReason].find(value=>typeof value==='string'&&value.trim());
 const buyer=message.from==='fruit-buyer'||message.from==='vegetable-buyer';
 return <li className={`chat-message ${buyer?'chat-outgoing':'chat-incoming'}`} data-message-id={message.id} data-speaker={message.from}><div className="chat-speaker"><span className="chat-avatar">{actor(message.from).split(' ').slice(0,2).map(word=>word[0]).join('')}</span><strong>{actor(message.from)}</strong><time dateTime={message.createdAt}>{new Date(message.createdAt).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',second:'2-digit',timeZone:'America/Los_Angeles'})}</time></div><div className="chat-bubble"><span className="chat-kind">{label}</span><p className="chat-text">{summary}</p>{detail&&<p className="chat-detail">{detail}</p>}{typeof recordedReason==='string'&&<p className="chat-detail"><strong>Reason:</strong> {recordedReason}</p>}<div className="chat-delivery">{(['sent','received','processed'] as const).map(stage=><span key={stage} className={message.transport[stage]?'confirmed':''}>{message.transport[stage]&&<Check size={9}/>} {stage}</span>)}{['failed','pending','cancelled'].includes(message.transport.status)&&<span>{message.transport.status}</span>}</div><details className="chat-details"><summary>Details</summary><p className="chat-detail">{roleName(message.from)} → {actor(message.to)} · {new Date(message.createdAt).toLocaleDateString('en-US',{timeZone:'America/Los_Angeles'})} · Pacific time</p><ReadableMessage message={message} catalog={catalog} skuId={skuId} messages={messages}/><details className="message-json"><summary>Message payload (JSON)</summary><pre tabIndex={0}>{JSON.stringify(message.payload,null,2)}</pre></details></details></div></li>;
}
